# Generated by Django 4.1.2 on 2022-10-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqoutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='author',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iqoutes.userfrom', verbose_name='username'),
        ),
    ]
