# Generated by Django 4.1.2 on 2022-10-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqoutes', '0002_quotes_author_alter_quotes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quotes',
            new_name='quote',
        ),
    ]
