# Generated by Django 4.1.2 on 2022-10-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqoutes', '0003_rename_quotes_quotes_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quote',
            new_name='text',
        ),
    ]
