# Generated by Django 4.1.2 on 2022-10-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqoutes', '0004_rename_quote_quotes_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='user',
        ),
    ]
